name: Build

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[RELEASE] ')"
    runs-on: ubuntu-latest
    steps:
      - id: get-version
        run: |
          plain=$(echo ${{ github.ref_name }} | cut -c 2-)
          echo "::set-output name=plain::$plain"
          major=$(echo ${{ github.ref_name }} | cut -c -2)
          echo "::set-output name=major::$major"
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Move to version branch
        run: |
          git checkout -b ${{ steps.get-version.outputs.plain }}
      - name: Set Git config
        run: |
          git config --global user.name 'GitHub Workflow'
          git config --global user.email '<>'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build using ncc
        run: |
          yarn ncc build main.js -o dist/main
          yarn ncc build post.js -o dist/post
      - name: Remove current tag
        run: |
          git tag -d ${{ github.ref_name }}
          git push --delete origin ${{ github.ref_name }}
      - name: Increase version
        run: |
          yarn config set version-git-message "[RELEASE] %s"
          yarn version --new-version ${{ steps.get-version.outputs.plain }}
          git stage .
          git push --set-upstream origin ${{ steps.get-version.outputs.plain }}
      - name: Push new tag
        run: |
          git push origin ${{ github.ref_name }}
      - name: Create or move parent tag
        run: |
          git tag -d ${{ steps.get-version.outputs.major }} || true
          git push --delete origin ${{ steps.get-version.outputs.major }} || true
          git tag ${{ steps.get-version.outputs.major }}
          git push origin ${{ steps.get-version.outputs.major }}
